import keyMirror from 'keymirror';

const ACTION_TYPES = keyMirror({
    CREATE_PRODUCT_REQUEST: null,
    CREATE_PRODUCT_SUCCESS: null,
    CREATE_PRODUCT_FAILURE: null,

    GET_PRODUCT_REQUEST: null,
    GET_PRODUCT_SUCCESS: null,
    GET_PRODUCT_FAILURE: null,

    GET_PRODUCT_LIST_REQUEST: null,
    GET_PRODUCT_LIST_SUCCESS: null,
    GET_PRODUCT_LIST_FAILURE: null,

    UPDATE_PRODUCT_REQUEST: null,
    UPDATE_PRODUCT_SUCCESS: null,
    UPDATE_PRODUCT_FAILURE: null,

    DELETE_PRODUCT_REQUEST: null,
    DELETE_PRODUCT_SUCCESS: null,
    DELETE_PRODUCT_FAILURE: null,

    FILTER_PRODUCT_REQUEST: null,
    FILTER_PRODUCT_SUCCESS: null,
    FILTER_PRODUCT_FAILURE: null
});

export default ACTION_TYPES;
