const actionConstants = {

    PRODUCT_CREATE_REQUEST: 'PRODUCT_CREATE_REQUEST',
    PRODUCT_CREATE_SUCCESS: 'PRODUCT_CREATE_SUCCESS',
    PRODUCT_CREATE_FAILURE: 'PRODUCT_CREATE_FAILURE',

    PRODUCT_DISPLAY_REQUEST: 'PRODUCT_DISPLAY_REQUEST',
    PRODUCT_DISPLAY_SUCCESS: 'PRODUCT_DISPLAY_SUCCESS',
    PRODUCT_DISPLAY_FAILURE: 'PRODUCT_DISPLAY_FAILURE',

    PRODUCT_DISPLAY_LIST_REQUEST: 'PRODUCT_DISPLAY_LIST_REQUEST',
    PRODUCT_DISPLAY_LIST_SUCCESS: 'PRODUCT_DISPLAY_LIST_SUCCESS',
    PRODUCT_DISPLAY_LIST_FAILURE: 'PRODUCT_DISPLAY_LIST_FAILURE',

    PRODUCT_SEARCH_REQUEST: 'PRODUCT_SEARCH_REQUEST',
    PRODUCT_SEARCH_SUCCESS: 'PRODUCT_SEARCH_SUCCESS',
    PRODUCT_SEARCH_FAILURE: 'PRODUCT_SEARCH_FAILURE',

    PRODUCT_UPDATE_REQUEST: 'PRODUCT_UPDATE_REQUEST',
    PRODUCT_UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
    PRODUCT_UPDATE_FAILURE: 'PRODUCT_UPDATE_FAILURE',

    PRODUCT_DELETE_REQUEST: 'PRODUCT_DELETE_REQUEST',
    PRODUCT_DELETE_SUCCESS: 'PRODUCT_DELETE_SUCCESS',
    PRODUCT_DELETE_FAILURE: 'PRODUCT_DELETE_FAILURE',

    PRODUCT_FILTER_REQUEST: 'PRODUCT_FILTER_REQUEST',
    PRODUCT_FILTER_SUCCESS: 'PRODUCT_FILTER_SUCCESS',
    PRODUCT_FILTER_FAILURE: 'PRODUCT_FILTER_FAILURE',

    FOUND_FLAG_RESET: 'FOUND_FLAG_RESET',
    CREATED_FLAG_RESET: 'CREATED_FLAG_RESET',
    UPDATED_FLAG_RESET: 'UPDATED_FLAG_RESET',
    DELETED_FLAG_RESET: 'DELETED_FLAG_RESET',

    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR',
};

export default actionConstants;
